# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HqyInteract - Touch enabled jQuery plugin that lets you create powerful interactions.
email: hqy321@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Touch enabled jQuery plugin that lets you create powerful interactions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rockcookies.github.io/hqy-interact" # the base hostname & protocol for your site
github_username:  rockcookies
version: 1.0.1
author: HQY

# Build settings
markdown: kramdown
